name = "PedestrianAvoidancePOMDP"
uuid = "a80ff0fe-e6a0-11e8-3b05-15413bd5ea7a"
repo = "https://github.com/sisl/PedestrianAvoidancePOMDP.jl"
version = "0.0.0"

[deps]
AutoUrban = "1385418a-9289-5a49-ab93-843b508de4cb"
AutoViz = "82aa6e0c-a491-5edf-8d4b-c16b98e4ea17"
AutomotiveDrivingModels = "99497e54-f3d6-53d3-a3a9-fa9315a7f1ba"
AutomotivePOMDPs = "dca8afc0-c686-11e8-0934-712707da73aa"
AutomotiveSensors = "9ec66b5e-c605-11e8-1454-ede748df6f96"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
QMDP = "3aa3ecc9-5a5d-57c8-8188-3e47bd8068d2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RLInterface = "3065fe53-3878-5aed-aae7-ab641be43734"
Records = "5984c134-fa48-5ed5-a57f-fc2f6936871f"
Reel = "71555da5-176e-5e73-a222-aebc6c6e4f2f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Vec = "44eeaf0b-fee4-471f-9310-ed6585cb3142"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
